services:
  - type: web
    name: contacts-manager-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
    autoDeploy: true