CREATE TABLE IF NOT EXISTS urls (
  id VARCHAR(255) PRIMARY KEY,
  original_url TEXT NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  user_id VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  visit_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS urls_slug_idx ON urls(slug);